export const EXCHANGE_TOKEN = 'EXCHANGE_TOKEN';
export const EXCHANGE_TOKEN_SUCCESS = 'EXCHANGE_TOKEN_SUCCESS';
export const EXCHANGE_TOKEN_LOADING = 'EXCHANGE_TOKEN_LOADING';
export const EXCHANGE_TOKEN_ERROR = 'EXCHANGE_TOKEN_ERROR';

export const FLUSH_PRODUCTS = 'FLUSH_PRODUCTS';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
